name: PR linter
run-name: PR linter

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  linter:
    name: Format and lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.0

      - name: Install dependencies and lint
        run: |
            yarn
            yarn lint
