name: Set tag and release
run-name: Set tag and release

on:
  workflow_dispatch: 
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**/*.yml'
      - '.gitignore'

permissions:
  checks: write
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Create Tag
        id: create-tag
        uses: jaywcjlove/create-tag-action@v1.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.create-tag.outputs.version }}
